package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"log"
	"os"
	"reflect"
	"strings"
	"text/template"
)

const criteriaTmpl = `// Code generated by gen-criteria. DO NOT EDIT.
package {{.Package}}

import "github.com/xplexer-lab/xplexer/internal/common/query"

var Fields = struct {
{{- range .Fields }}
	{{.Name}} query.{{.Headers}}Field
{{- end }}
}{
{{- range .Fields }}
	{{.Name}}: "{{.DBName}}",
{{- end }}
}
`

type FieldData struct {
	Name   string
	Type   string
	DBName string
}

func main() {
	var (
		sourceFile = flag.String("source", "", "Path to the file containing State struct")
		structName = flag.String("struct", "State", "Name of the struct to parse")
		outputFile = flag.String("output", "criteria_gen.go", "Output file name")
	)
	flag.Parse()

	if *sourceFile == "" {
		log.Fatal("Please provide -source file path")
	}

	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, *sourceFile, nil, parser.ParseComments)
	if err != nil {
		log.Fatal(err)
	}

	var fields []FieldData
	var pkgName string

	pkgName = node.Name.Name

	ast.Inspect(node, func(n ast.Node) bool {
		t, ok := n.(*ast.TypeSpec)
		if !ok || t.Name.Name != *structName {
			return true
		}

		st, ok := t.Type.(*ast.StructType)
		if !ok {
			return true
		}

		for _, field := range st.Fields.List {
			if len(field.Names) == 0 {
				continue
			}

			goFieldName := field.Names[0].Name

			fieldType := "String"
			switch typeName(field.Type) {
			case "int", "int64", "int32":
				fieldType = "Int"
			case "bool":
				fieldType = "Bool"
			case "Time", "time.Time":
				fieldType = "Time"
			}

			dbTag := ""
			if field.Tag != nil {
				tagValue := strings.ReplaceAll(field.Tag.Value, "`", "")
				tag := reflect.StructTag(tagValue)
				dbTag = tag.Get("db")
			}
			if dbTag == "" {
				dbTag = strings.ToLower(goFieldName)
			}

			fields = append(fields, FieldData{
				Name:   goFieldName,
				Type:   fieldType,
				DBName: dbTag,
			})
		}
		return false
	})

	f, err := os.Create(*outputFile)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()

	tmpl := template.Must(template.New("criteria").Parse(criteriaTmpl))
	if err := tmpl.Execute(f, map[string]any{
		"Package": pkgName,
		"Fields":  fields,
	}); err != nil {
		log.Fatal(err)
	}

	fmt.Printf("Generated criteria for %s in %s\n", *structName, *outputFile)
}

func typeName(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return t.Name
	case *ast.SelectorExpr:
		return typeName(t.X) + "." + t.Sel.Name
	default:
		return "String"
	}
}
